### ISSUE TITLE
Making the new facial model work 

### ISSUE THREAD

**Issue by whatevergeek** [bigdatasg/ai_from_data_to_device#16]
This is to track the exercise to make the facial model work on pi

**Comment by whatevergeek** [comment]
@weiyangwang 

I tried the model file we tested the other day on the pi with latest coral edgetpu library.
I got the following new error:

Traceback (most recent call last):
  File "coral_live_image_classification.py", line 87, in <module>
    main()
  File "coral_live_image_classification.py", line 65, in main
    results = engine.ClassifyWithImage(image, top_k=1)
  File "/usr/lib/python3/dist-packages/edgetpu/utils/warning.py", line 44, in new_func
    return func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/edgetpu/classification/engine.py", line 127, in ClassifyWithImage
    return self.classify_with_image(img, threshold, top_k, resample)
  File "/usr/lib/python3/dist-packages/edgetpu/classification/engine.py", line 89, in classify_with_image
    return self.classify_with_input_tensor(input_tensor, threshold, top_k)
  File "/usr/lib/python3/dist-packages/edgetpu/classification/engine.py", line 113, in classify_with_input_tensor
    input_tensor)
  File "/usr/lib/python3/dist-packages/edgetpu/basic/basic_engine.py", line 121, in run_inference
    result = self._engine.RunInference(input)
  File "/usr/lib/python3/dist-packages/edgetpu/swig/edgetpu_cpp_wrapper.py", line 111, in RunInference
    return _edgetpu_cpp_wrapper.BasicEnginePythonWrapper_RunInference(self, input)
RuntimeError: external/org_tensorflow/tensorflow/lite/core/subgraph.cc:901 required_bytes != bytes (307200 != 76800)


Is there an expected graph resolution to make this work?

**Comment by whatevergeek** [comment]
@weiyangwang 
would you be able to help send PR (compiled facial edgetpu model and facial_labels.txt) here: https://github.com/bigdatasg/ai_from_data_to_device/tree/master/coral_workshop

**Comment by whatevergeek** [comment]
@weiyangwang 
just an fyi.
when running the script in the new edgetpu version, i had to run it like the following:    

LD_PRELOAD=/usr/lib/arm-linux-gnueabihf/libatomic.so.1 python3 coral_live_image_classification.py --model test_data/facial_model_int_quant_edgetpu.tflite --label test_data/facial_labels.txt
